# action.yml
name: 'MOFE upload'
description: 'テストケースと問題文を MOFE にアップロードします'
inputs:
  mofe_username:
    description: 'アップロードに使用する MOFE のアカウントのユーザー名'
    required: true
  mofe_password:
    description: 'アップロードに使用する MOFE のアカウントのパスワード'
    required: true
  upload_testcases:
    description: 'テストケースをアップロードするかどうか'
    required: false
    default: 'true'
  upload_statement:
    description: '問題文をアップロードするかどうか'
    required: false
    default: 'true'
  force_upload_statement:
    description: '問題文をアップロードする際に、既存の問題名と異なる問題をアップロードするかどうか'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
